services:
  postgres:
    image: postgres:15.4
    container_name: awesome-postgres
    restart: always
    environment:
      POSTGRES_USER: awesomeuser
      POSTGRES_PASSWORD: awesomepass
      POSTGRES_DB: awesomedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awesomeuser -d awesomedb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: awesome-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000 --tcp-keepalive 60 --rdbcompression yes --rdbchecksum yes --activerehashing yes --hz 100 --dynamic-hz yes --timeout 0 --tcp-backlog 511
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data: